### ISSUE TITLE
Exit if wrong file is loaded (not an error)

### ISSUE THREAD

**Issue by kojix2** [ankane/blingfire#1]
Hi! @ankane 

Today I used Blingfire to run GPT-2 on Windows. 
I enjoy inference with Deep Learning in Ruby using the ecosystem you have created. 
https://twitter.com/2xijok/status/1568483347382562817

I found a behavior that is a little worrisome and I would like to report it.

## Step to reproduce

```
git clone https://github.com/ankane/blingfire-ruby.git
cd blingfire-ruby
bundle install
bundle exec rake vendor:all download:models
bundle exec rake test
```

Then:

```
model = BlingFire.load_model("README.md") # nonsense
```

It exits abnormally without generating an error; on Windows, no message appears in the terminal. In the case of Ubuntu, the following message is displayed and the program exits.

```console
terminate called after throwing an instance of 'std::runtime_error'
  what():  /__w/ml-builds/ml-builds/BlingFire/blingfireclient.library/src/FALDB.cpp, 41: assertion failed: 0 <= Count && Count <= FALimits::MaxLdbDumpCount
```

## Expected behavior

Raises an error instead of abruptly terminating abnormally.

## Look into it a little more

Error occurs here.
https://github.com/ankane/blingfire-ruby/blob/b1bc17c6a62d03fa5146a246b7e1b76c26841c31/lib/blingfire/model.rb#L7

Perhaps this is not a bringfire-ruby or bringfire issue, but a [Fiddle](https://github.com/ruby/fiddle) issue. It seems you are creating a shared library from C++ code and calling it with Fiddle.

@kou. Thanks for all your help. I would like to ask your opinion from your expert knowledge if there is any way to prevent Fiddle from terminating abnormally and raising an error.

**Comment by ankane** [comment]
Hey @kojix2, thanks for reporting. There's no way to rescue C++ exceptions with FFI, so this would need to be addressed in Bling Fire (basically, a C API should not throw any exceptions).

I reported a similar issue with missing files in https://github.com/microsoft/BlingFire/issues/46.

**Comment by ankane** [comment]
Cleaning up issues (needs to be fixed upstream).
