### ISSUE TITLE
Report on the creation of the Crystal port

### ISSUE THREAD

**Issue by kojix2** [ankane/blingfire#2]
Hi @ankane 

I have ported this wonderful library to [blingfire-crystal](https://github.com/kojix2/blingfire-crystal). 
And blingfire-ruby is used in the LibUI [example](https://github.com/kojix2/LibUI/blob/main/examples/gpt2_notepad.rb).
I learn a lot reading the code you write.

I wish you all the best. Thank you.

**Comment by ankane** [comment]
Great to hear, thanks @kojix2!
